CREATE TABLE BILLDETAILTYPE (
  BDTYPE INT NOT NULL,
  BDTYPENAME VARCHAR(20),
  CONSTRAINT BILLDETAILTYPE PRIMARY KEY (BDTYPE)
);

CREATE TABLE COUNTRY (
  COUNTRYID INT,
  COUNTRYNAME VARCHAR(30),
  CONSTRAINT COUNTRY_PK PRIMARY KEY ( COUNTRYID )
);


CREATE TABLE CITY(
  CID INT,
  CName VARCHAR(50),
  COUNTRYID INT,
  CONSTRAINT CITY_PK PRIMARY KEY (CID),
  CONSTRAINT CITY_FK_COUNTRYID FOREIGN KEY (COUNTRYID) REFERENCES COUNTRY(COUNTRYID)
);


CREATE TABLE USERROLE (
  UROLE INT,
  ROLENAME VARCHAR(20),
  CONSTRAINT USERROLE_PK PRIMARY KEY ( UROLE )
); 

CREATE TABLE DORMUSER (
  USERID VARCHAR(255) NOT NULL,
  FNAME VARCHAR(30),
  LNAME VARCHAR(30),
  USERNAME VARCHAR(30) NOT NULL,
  UPASSWORD VARCHAR(40) NOT NULL,
  UTEL VARCHAR(10),
  UROLE INT NOT NULL,
  SEX CHAR(1) NOT NULL,
  CONSTRAINT DORMUSER_PK PRIMARY KEY ( USERID ),
  CONSTRAINT DORMUSER_UNIQUE_USERNAME UNIQUE ( USERNAME ),
  CONSTRAINT DORMUSER_FK_UROLE FOREIGN KEY (UROLE) REFERENCES USERROLE(UROLE),
  CONSTRAINT DORMUSER_CHECK_SEX CHECK (SEX = 'F' OR SEX = 'M' OR SEX ='N')
);

CREATE TABLE DORM (
  DID INT NOT NULL,
  DNAME VARCHAR(30) NOT NULL,
  DDESCRIPTION CLOB,
  DLOCATION CLOB NOT NULL,
  CID INT NOT NULL,
  USERID VARCHAR(255) NOT NULL,
  CONSTRAINT DORM_PK PRIMARY KEY ( DID ),
  CONSTRAINT DORM_FK_USERID FOREIGN KEY (USERID) REFERENCES DORMUSER(USERID),
  CONSTRAINT DORM_FK_CID FOREIGN KEY (CID) REFERENCES CITY(CID)
);

CREATE TABLE ROOMTYPE (
  RID INT NOT NULL,
  RNAME VARCHAR(30) NOT NULL,
  RPRICE INT NOT NULL,
  RSIZE INT,
  DID INT NOT NULL,
  constraint  ROOMTYPE_PK PRIMARY KEY 
  (
    DID 
  , RID 
  ),
  CONSTRAINT ROOMTYPE_FK_DID FOREIGN KEY (DID) REFERENCES DORM(DID)
);

CREATE TABLE FacilityList (
  FID INT NOT NULL,
  Ftype VARCHAR(30),
  CONSTRAINT FACILITYLIST_PK PRIMARY KEY (FID)
);


CREATE TABLE FacilityDorm (
  FID INT NOT NULL,
  DID INT NOT NULL,
  CONSTRAINT FACILITYDORM_PK PRIMARY KEY (FID, DID),
  CONSTRAINT FACILITYDORM_FK_FID FOREIGN KEY (FID) REFERENCES FACILITYLIST(FID),
  CONSTRAINT FACILITYDORM_FK_DID FOREIGN KEY (DID) REFERENCES Dorm(DID)
);

CREATE TABLE CONTRACT (
  ContractID INT NOT NULL,
  CStartDate DATE NOT NULL,
  CEndDate DATE NOT NULL,
  CDeposite INT,
  CPrice INT,
  CRoomNo VARCHAR(20),
  RID INT NOT NULL,
  DID INT NOT NULL,
  USERID VARCHAR(255) NOT NULL,
  CONSTRAINT CONTRACT_PK PRIMARY KEY (ContractID),
  CONSTRAINT CONTRACT_FK_DID FOREIGN KEY (DID) REFERENCES Dorm(DID),
  CONSTRAINT CONTRACT_FK_USERID FOREIGN KEY (USERID) REFERENCES DORMUSER(USERID)
  
);

CREATE TABLE BILL (
  BID INT NOT NULL,
  BStartDate DATE NOT NULL,
  BEndDate DATE NOT NULL,
  BTotal INT,
  BStatus INT DEFAULT 0,
  ContractID INT NOT NULL,
  CONSTRAINT BILL_PK PRIMARY KEY (BID),
  CONSTRAINT BILL_FK_CONTRACTID FOREIGN KEY (ContractID) REFERENCES CONTRACT(ContractID)
);


CREATE TABLE BILLDETAIL (
  BDID INT NOT NULL,
  BDName VARCHAR(10),
  BDPrice INT,
  BDType INT,
  DID INT,
  CONSTRAINT BILLDETAIL_PK PRIMARY KEY (BDID),
  CONSTRAINT BILLDETAIL_FK_BDTYPE FOREIGN KEY (BDType) REFERENCES BILLDETAILTYPE (BDType),
  CONSTRAINT BILLDETAIL_FK_DID FOREIGN KEY (DID) REFERENCES DORM(DID)
);



CREATE TABLE BILLLIST (
  BID INT NOT NULL,
  BDID INT NOT NULL,
  BLUnit INT,
  BLTotal INT,
  CONSTRAINT BILLLIST_PK PRIMARY KEY (BID,BDID),
  CONSTRAINT BILLLIST_FK_BID FOREIGN KEY (BID) REFERENCES BILL(BID),
  CONSTRAINT BILLLIST_FK_BDID FOREIGN KEY (BDID) REFERENCES BILLDETAIL(BDID)

);